### PR TITLE
Generate valid fiscal codes.

### LINKED ISSUE #209: Bug: i codici fiscali generati automaticamente non sono validi
Se un file users.json non viene trovato, il testenv2 ne genera automaticamente uno con dati casuali. Il codice fiscale viene generato in questo modo:

```python
                fiscal_number = exrex.getone(
                    r'[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]'
                )
```

e quindi non è conforme alle regole sintattiche. Questo può causare facilmente problemi nella lettura di questo dato presso il Service Provider.

### PR DESCRIPTION
**Pull request by bfabio**
Generate valid fiscal codes when no users.json is available.

Fix #209.

### CODE REVIEW

**Comment by bfabio** [comment]
The pipeline should pass once #248 is checked in.

**Comment by alranel** [comment]
The build fails so I can't merge this. Are you able to look into this by any chance? Thank you :)

**Comment by bfabio** [comment]
@alranel Sure. This needs #248 because I didn't bother adding Python 2 compatibility.

Besides that, I rebased but there are still a couple issues. I'll look into them ASAP.

**Comment by bfabio** [comment]
@alranel Done. I also added Python 2 compatibility so that it doesn't depend on #248 anymore, allowing us to not rush the merge of #248.

**Comment by fmarco** [comment]
@bfabio rebase on master pls

**Comment by bfabio** [comment]
@fmarco Done.

**Comment by bfabio** [comment]
@sebbalex this can go in, it's pretty straightforward. flake8 fails for code unrelated to this PR.

**Review by sebbalex — APPROVED** [review]
🎉

**Pull request merged**
