### PR TITLE
[WiP] Python3.8 setup

### PR DESCRIPTION
**Pull request by peppelinux**
Minor changes related to Py38 setup.
Work in progress

### CODE REVIEW

**Comment by bfabio** [comment]
Hi @peppelinux, I think we should just drop the multi Python support and focus on Docker as the only installation method.

`requirements.txt` right now is a assuming a specific version anyway (which one I don't even know, probably a mixture of versions of whoever ran pip-compile over time).

**Comment by fmarco** [comment]
Why not keeping both?

docker is convenient but maybe in some cases people need a lighter installation.

**Comment by peppelinux** [comment]
I completely agree about the Docker strategy, at the same time python virtualenv can be considered like a kind of "container" and probably it would be better for development needs. Docker must be the first solution, development virtualenv is the way to do things, patch and join with the material development of the platform.

With this PR I just share some notes (it could be just a draft and nothing more). If we would go with this line we could update the Docker image with a py38 environment, and not at last, I'd like to use Alpine Linux as distribution for docker because it's thin and better for performances

**Comment by peppelinux** [comment]
We also should drop support for py34 and py35 if you agree

**Comment by peppelinux** [comment]
@bfabio That's the reason why we found troubles with py38
https://github.com/italia/spid-testenv2/pull/312/checks?check_run_id=1665478996#step:5:124

it's lxml, as we talked about, it had to be him!

**Pull request closed without merging**
